import bcrypt from "bcryptjs";
import { PrismaClient, UserRole } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  {
    "name": "Сеты",
    "slug": "sets",
    "sortOrder": 1
  },
  {
    "name": "Суши",
    "slug": "sushi",
    "sortOrder": 2
  },
  {
    "name": "Пицца",
    "slug": "pizza",
    "sortOrder": 3
  },
  {
    "name": "Закуски",
    "slug": "snacks",
    "sortOrder": 4
  },
  {
    "name": "Напитки",
    "slug": "drinks",
    "sortOrder": 5
  }
] as const;

const menuItems = [
  {
    "id": "seed-sets-001",
    "categorySlug": "sets",
    "name": "Рамадан",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍕 Пеперони-1 шт\n🍕 Маргарита-1 шт\n🍕 4 Сезона-1 шт\n🍗 Крылышки-16 шт\n\n🎁 Фри + Кола 2л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Ramadan.jpeg",
    "sellingPrice": 12500,
    "costPrice": 8500,
    "setBuilderPrice": 12500,
    "weight": "🍣 30 шт суши + 3 шт Пицца, Крылышки + 🎁",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍕 Пеперони-1 шт\n🍕 Маргарита-1 шт\n🍕 4 Сезона-1 шт\n🍗 Крылышки-16 шт\n\n🎁 Фри + Кола 2л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-002",
    "categorySlug": "sets",
    "name": "Ауызашар",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 20 шт\n🍣 Канада — 10 шт\n🍕 Пеперони-1 шт\n🍕 Маргарита-1 шт\n🍗 Крылышки-8 шт\n\n🎁 Фри + Кола 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-AuyzAshar.jpeg",
    "sellingPrice": 9990,
    "costPrice": 6790,
    "setBuilderPrice": 9990,
    "weight": "🍣 40 шт суши + 2 шт Пицца, Крылышки + 🎁",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 20 шт\n🍣 Канада — 10 шт\n🍕 Пеперони-1 шт\n🍕 Маргарита-1 шт\n🍗 Крылышки-8 шт\n\n🎁 Фри + Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-003",
    "categorySlug": "sets",
    "name": "Олигарх",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 10 шт\n🍕 Пеперони-1 шт\n\n🎁 Крылышки",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Oligarh.jpg",
    "sellingPrice": 6490,
    "costPrice": 4410,
    "setBuilderPrice": 6490,
    "weight": "🍣 20 шт суши + Пицца, Крылышки",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 10 шт\n🍕 Пеперони-1 шт\n\n🎁 Крылышки",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-004",
    "categorySlug": "sets",
    "name": "Старт",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка - 10 шт\n🌭 Корн-дог - 5 шт\n🟡 Шарики - 15 шт\n🍕 Пеперони - 1 шт\n\n🎁 Кола 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Start.jpg",
    "sellingPrice": 6990,
    "costPrice": 4750,
    "setBuilderPrice": 6990,
    "weight": "🍣 30 шт суши + Корн-дог, Пицца, Шарики",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка - 10 шт\n🌭 Корн-дог - 5 шт\n🟡 Шарики - 15 шт\n🍕 Пеперони - 1 шт\n\n🎁 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-005",
    "categorySlug": "sets",
    "name": "Зал",
    "description": "🍣 Цезарь — 10 шт\n🍣 Америка — 20 шт\n🍣 Красный зверь — 10 шт\n🍕 Пеперони - 1 шт\n\n🎁 Кола 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Zal.jpg",
    "sellingPrice": 6990,
    "costPrice": 4750,
    "setBuilderPrice": 6990,
    "weight": "🍣 40 шт суши + Пицца",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Америка — 20 шт\n🍣 Красный зверь — 10 шт\n🍕 Пеперони - 1 шт\n\n🎁 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-006",
    "categorySlug": "sets",
    "name": "Техас",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Америка — 10 шт\n🥤 Кола 1л\n\n🎁 🍔Бургер - 1шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Texas.jpg",
    "sellingPrice": 5990,
    "costPrice": 4070,
    "setBuilderPrice": 5990,
    "weight": "🍣 30 шт суши + 🍔Бургер",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Америка — 10 шт\n🥤 Кола 1л\n\n🎁 🍔Бургер - 1шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-007",
    "categorySlug": "sets",
    "name": "Титаник",
    "description": "🍣 Цезарь — 10 шт\n🍣 Филадельфия — 10 шт\n\n🍗 Крылышки - 14 шт\n🍟 Фри + шарики\n🥤 Кола 1л\n\n",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Titanik.jpg",
    "sellingPrice": 11500,
    "costPrice": 7820,
    "setBuilderPrice": 11500,
    "weight": "🍣 20 шт суши + 🍕2пицца, крылышки, шарики, фри + 🎁",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Филадельфия — 10 шт\n\n🍗 Крылышки - 14 шт\n🍟 Фри + шарики\n🥤 Кола 1л\n\n",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-008",
    "categorySlug": "sets",
    "name": "Бинго",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Калифорния запеченный — 10 шт\n🍣 Цезарь Запеченный — 10 шт\n🍣 Каппа Маки - 10 шт\n🍣 Сяке Маки - 10 шт\n\n🍕 Микс - 1 шт\n🍕 Четыре сыра - 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Bingo.jpg",
    "sellingPrice": 10990,
    "costPrice": 7470,
    "setBuilderPrice": 10990,
    "weight": "🍣 50 шт суши + 🍕2 шт Пицца",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Калифорния запеченный — 10 шт\n🍣 Цезарь Запеченный — 10 шт\n🍣 Каппа Маки - 10 шт\n🍣 Сяке Маки - 10 шт\n\n🍕 Микс - 1 шт\n🍕 Четыре сыра - 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-009",
    "categorySlug": "sets",
    "name": "На двоих",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍕 Пеперони - 1 шт\n\n🎁 🍟Фри",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-NaDvoih.jpg",
    "sellingPrice": 5990,
    "costPrice": 4070,
    "setBuilderPrice": 5990,
    "weight": "🍣 20 шт суши, 🍕Пицца + 🍟Фри",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍕 Пеперони - 1 шт\n\n🎁 🍟Фри",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-010",
    "categorySlug": "sets",
    "name": "Родной",
    "description": "🍣 Америка — 20 шт\n🍣 Цезарь — 30 шт\n🍣 Запечённый — 10 шт\n🍣 Зелёный зверь — 10 шт\n🍣 Калифорния — 10 шт\n\n🍕 Пепперони\n🍕 Сырная\n\n🍟 Фри\n\n🎁 2.5 л лимонад в подарок 😍😍",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Rodnoi.jpg",
    "sellingPrice": 11990,
    "costPrice": 8150,
    "setBuilderPrice": 11990,
    "weight": "🍣 80 шт суши, 🍕 2 пиццы + 🍟 фри",
    "ingredients": "🍣 Америка — 20 шт\n🍣 Цезарь — 30 шт\n🍣 Запечённый — 10 шт\n🍣 Зелёный зверь — 10 шт\n🍣 Калифорния — 10 шт\n\n🍕 Пепперони\n🍕 Сырная\n\n🍟 Фри\n\n🎁 2.5 л лимонад в подарок 😍😍",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-011",
    "categorySlug": "sets",
    "name": "Антарктида",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Крылышки — 14 шт\n\n🍟 Фри — 2 шт\n\n🍕 Пеперони — 2 шт\n\n🎁 Кола — 2 л в подарок 😍",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Antarktida.jpg",
    "sellingPrice": 9990,
    "costPrice": 6790,
    "setBuilderPrice": 9990,
    "weight": "🍣 20 шт суши + 🍗 14 шт крылышки, 🍟 2 шт фри, 🍕 2 пиццы",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Крылышки — 14 шт\n\n🍟 Фри — 2 шт\n\n🍕 Пеперони — 2 шт\n\n🎁 Кола — 2 л в подарок 😍",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-012",
    "categorySlug": "sets",
    "name": "Шейх",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Аляска — 10 шт\n🍣 Америка — 10 шт\n🍣 Калифорния запечённый — 10 шт\n\n🍗 Нагетсы — 6 шт\n\n🍟 Фри — 1 шт\n\n🍕 Пеперони — 1 шт\n🍕 4 сезона — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Sheix.jpg",
    "sellingPrice": 9990,
    "costPrice": 6790,
    "setBuilderPrice": 9990,
    "weight": "🍣 50 шт суши + 🍗 6 шт нагетсы + 🍟 фри + 🍕 2 пиццы",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Аляска — 10 шт\n🍣 Америка — 10 шт\n🍣 Калифорния запечённый — 10 шт\n\n🍗 Нагетсы — 6 шт\n\n🍟 Фри — 1 шт\n\n🍕 Пеперони — 1 шт\n🍕 4 сезона — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-013",
    "categorySlug": "sets",
    "name": "Буря",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🎁 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Bura.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 40 шт суши + 🍕 пеперони + 🥤 кола 1 л",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🎁 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-014",
    "categorySlug": "sets",
    "name": "Бамбук",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍘 Саше — 4 шт\n🍣 Гунканы — 4 шт\n\n🍕 Пеперони — 2 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Bambuk.jpg",
    "sellingPrice": 8490,
    "costPrice": 5770,
    "setBuilderPrice": 8490,
    "weight": "🍣 38 шт суши + 🍕 2 пиццы",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍘 Саше — 4 шт\n🍣 Гунканы — 4 шт\n\n🍕 Пеперони — 2 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-015",
    "categorySlug": "sets",
    "name": "Паладин",
    "description": "🍣 Цезарь — 40 шт\n🍣 Цезарь запечённый — 20 шт\n🍣 Америка — 20 шт\n\n🍕 Пеперони — 2 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Paladin.jpg",
    "sellingPrice": 11500,
    "costPrice": 7820,
    "setBuilderPrice": 11500,
    "weight": "🍣 80 шт суши + 🍕 2 пиццы",
    "ingredients": "🍣 Цезарь — 40 шт\n🍣 Цезарь запечённый — 20 шт\n🍣 Америка — 20 шт\n\n🍕 Пеперони — 2 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-016",
    "categorySlug": "sets",
    "name": "Париж",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Америка — 10 шт\n\n🍗 Нагетсы — 8 шт\n\n🍕 Пеперони — 1 шт\n\n🎁 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Paris.jpg",
    "sellingPrice": 7990,
    "costPrice": 5430,
    "setBuilderPrice": 7990,
    "weight": "🍣 30 шт суши + 🍗 8 шт нагетсы + 🍕 пеперони + 🥤 кола 1 л",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Америка — 10 шт\n\n🍗 Нагетсы — 8 шт\n\n🍕 Пеперони — 1 шт\n\n🎁 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-017",
    "categorySlug": "sets",
    "name": "Хот",
    "description": "🍣 Цезарь — 10 шт\n🍣 Америка лосось — 10 шт\n🍣 Фирмен ПАК ролл — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Крылышки — 14 шт\n\n🍕 Пицца грибная — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Xot.jpg",
    "sellingPrice": 8990,
    "costPrice": 6110,
    "setBuilderPrice": 8990,
    "weight": "🍣 40 шт суши + 🍗 14 шт крылышки + 🍕 грибная",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Америка лосось — 10 шт\n🍣 Фирмен ПАК ролл — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Крылышки — 14 шт\n\n🍕 Пицца грибная — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-018",
    "categorySlug": "sets",
    "name": "Нокдаун",
    "description": "🍣 Цезарь — 20 шт\n🍣 Капа маки — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Салатный ролл — 10 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Nokdaun.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 60 шт суши + 🍕 пеперони",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Капа маки — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Салатный ролл — 10 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-019",
    "categorySlug": "sets",
    "name": "Лондон",
    "description": "🍣 Цезарь запечённый — 20 шт\n\n🍟 Фри — 2 шт\n\n🍗 Крылышки — 14 шт\n\n🎁 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-London.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 20 шт суши + 🍟 фри + 🍗 крылышки + 🥤 кола 1 л",
    "ingredients": "🍣 Цезарь запечённый — 20 шт\n\n🍟 Фри — 2 шт\n\n🍗 Крылышки — 14 шт\n\n🎁 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-020",
    "categorySlug": "sets",
    "name": "Жареный",
    "description": "🍣 Америка — 20 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍘 Саше — 4 шт\n\n🍕 Пеперони — 1 шт\n🍕 Маргарита — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Jarenni.jpg",
    "sellingPrice": 8990,
    "costPrice": 6110,
    "setBuilderPrice": 8990,
    "weight": "🍣 44 шт суши + 🍕 2 пиццы",
    "ingredients": "🍣 Америка — 20 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍘 Саше — 4 шт\n\n🍕 Пеперони — 1 шт\n🍕 Маргарита — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-021",
    "categorySlug": "sets",
    "name": "Токио",
    "description": "🍣 Цезарь запечённый — 10 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт\n\n🍗 Крылышки — 7 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Tokio.jpg",
    "sellingPrice": 5990,
    "costPrice": 4070,
    "setBuilderPrice": 5990,
    "weight": "🍣 10 шт суши + 🍕 4 сезона + 🍟 фри + 🍗 крылышки",
    "ingredients": "🍣 Цезарь запечённый — 10 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт\n\n🍗 Крылышки — 7 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-022",
    "categorySlug": "sets",
    "name": "Сеул",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Америка — 10 шт\n🍣 Гункан с лососем — 4 шт\n🍘 Саше с курицей — 4 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Seul.jpg",
    "sellingPrice": 8490,
    "costPrice": 5770,
    "setBuilderPrice": 8490,
    "weight": "🍣 38 шт суши + 🍕 пеперони",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Америка — 10 шт\n🍣 Гункан с лососем — 4 шт\n🍘 Саше с курицей — 4 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-023",
    "categorySlug": "sets",
    "name": "Голд",
    "description": "🍣 Цезарь запечённый — 20 шт\n🍘 Саше — 4 шт\n\n🍗 Крылышки — 14 шт\n\n🟡 Шарики — 1 шт\n🌭 Корн дог — 5 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Gold.jpg",
    "sellingPrice": 8490,
    "costPrice": 5770,
    "setBuilderPrice": 8490,
    "weight": "🍣 20 шт суши + 🍘 саше + 🍗 14 шт крылышки + 🟡 шарики + 🌭 корн дог",
    "ingredients": "🍣 Цезарь запечённый — 20 шт\n🍘 Саше — 4 шт\n\n🍗 Крылышки — 14 шт\n\n🟡 Шарики — 1 шт\n🌭 Корн дог — 5 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-024",
    "categorySlug": "sets",
    "name": "Солнечный",
    "description": "🍣 Цезарь запечённый — 10 шт\n🍣 Калифорния запечённый — 10 шт\n🍣 Капа маки запечённый — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Solnechni.jpg",
    "sellingPrice": 6990,
    "costPrice": 4750,
    "setBuilderPrice": 6990,
    "weight": "🍣 40 шт суши + 🍕 пеперони",
    "ingredients": "🍣 Цезарь запечённый — 10 шт\n🍣 Калифорния запечённый — 10 шт\n🍣 Капа маки запечённый — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-025",
    "categorySlug": "sets",
    "name": "Босфор",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Bosfor.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 40 шт суши + 🍕 4 сезона + 🍟 фри",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-026",
    "categorySlug": "sets",
    "name": "Алмаарасан",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🌭 Корн дог — 1 шт\n🍗 Нагетсы — 8 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Almaarasan.jpg",
    "sellingPrice": 8990,
    "costPrice": 6110,
    "setBuilderPrice": 8990,
    "weight": "🍣 40 шт суши + 🌭 корн дог + 🍗 нагетсы + 🍕 4 сезона + 🍟 фри",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🌭 Корн дог — 1 шт\n🍗 Нагетсы — 8 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-027",
    "categorySlug": "sets",
    "name": "Дубай",
    "description": "🍣 Фирмен ПАК ролл — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Нагетсы — 8 шт\n\n🍟 Фри — 1 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Dubai.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 20 шт суши + 🍗 нагетсы + 🍟 фри + 🍕 пеперони",
    "ingredients": "🍣 Фирмен ПАК ролл — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Нагетсы — 8 шт\n\n🍟 Фри — 1 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-028",
    "categorySlug": "sets",
    "name": "Эврика",
    "description": "🍣 Цезарь — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Фирмен ПАК ролл — 10 шт\n\n🍕 4 сезона — 1 шт\n\n🎁🥤 Кола — 1 л (в подарок)",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Evrika.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 40 шт суши + 🍕 4 сезона + 🎁🥤 кола 1 л",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Фирмен ПАК ролл — 10 шт\n\n🍕 4 сезона — 1 шт\n\n🎁🥤 Кола — 1 л (в подарок)",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-029",
    "categorySlug": "sets",
    "name": "Позитив",
    "description": "🍣 Цезарь — 10 шт\n🍣 Темпура — 10 шт\n\n🍗 Крылышки — 14 шт\n\n🍕 Пицца куриная — 1 шт\n\n🎁 В подарок: 🍟 Фри",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Pozitiv.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 20 шт суши + 🍟 фри + 🍗 крылышки + 🍕 куриная",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Темпура — 10 шт\n\n🍗 Крылышки — 14 шт\n\n🍕 Пицца куриная — 1 шт\n\n🎁 В подарок: 🍟 Фри",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-030",
    "categorySlug": "sets",
    "name": "Пекин",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Ролл с огурцами — 10 шт\n\n🍕 4 сезона — 1 шт\n🍕 Пеперони — 1 шт\n\n🎁 В подарок: 🍟 Фри — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Pekin.jpg",
    "sellingPrice": 8490,
    "costPrice": 5770,
    "setBuilderPrice": 8490,
    "weight": "🍣 40 шт суши + 🍕 2 пиццы + 🎁 фри",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Ролл с огурцами — 10 шт\n\n🍕 4 сезона — 1 шт\n🍕 Пеперони — 1 шт\n\n🎁 В подарок: 🍟 Фри — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-031",
    "categorySlug": "sets",
    "name": "4 You",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Сырный ролл — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Америка с лососем — 10 шт\n\n🍘 Саше — 4 шт\n\n🍗 Нагетсы — 8 шт\n\n🟡 Шарики — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-4You.jpg",
    "sellingPrice": 7700,
    "costPrice": 5240,
    "setBuilderPrice": 7700,
    "weight": "🍣 40 шт суши + 🍘 саше + 🍗 нагетсы + 🟡 шарики",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Сырный ролл — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Америка с лососем — 10 шт\n\n🍘 Саше — 4 шт\n\n🍗 Нагетсы — 8 шт\n\n🟡 Шарики — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-032",
    "categorySlug": "sets",
    "name": "Пикник",
    "description": "🍣 Филадельфия классик — 20 шт\n🍣 Америка — 20 шт\n🍣 Зелёный зверь — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Фирменный Пакролл — 10 шт\n🍣 Цезарь темпура — 20 шт\n🍣 Бонито — 10 шт\n\n🍕 Пицца Пеперони\n🍕 Пицца 4 сезона ",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Piknik.jpg",
    "sellingPrice": 14490,
    "costPrice": 9850,
    "setBuilderPrice": 14490,
    "weight": "100шт суши, в подарок 🎁2пиццы",
    "ingredients": "🍣 Филадельфия классик — 20 шт\n🍣 Америка — 20 шт\n🍣 Зелёный зверь — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Фирменный Пакролл — 10 шт\n🍣 Цезарь темпура — 20 шт\n🍣 Бонито — 10 шт\n\n🍕 Пицца Пеперони\n🍕 Пицца 4 сезона ",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-033",
    "categorySlug": "sets",
    "name": "Сочный",
    "description": "🍣 Филадельфия классик — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Гейша — 10 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🎁 В подарок:\n🍕 Пицца Пеперони\n🍕 Пицца 4 сезона\n🍕 Пицца Маргарита",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Sochni.jpg",
    "sellingPrice": 12990,
    "costPrice": 8830,
    "setBuilderPrice": 12990,
    "weight": "🍣 70 шт суши  + 🎁🍕 3 пиццы",
    "ingredients": "🍣 Филадельфия классик — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Гейша — 10 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🎁 В подарок:\n🍕 Пицца Пеперони\n🍕 Пицца 4 сезона\n🍕 Пицца Маргарита",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-034",
    "categorySlug": "sets",
    "name": "Пинто",
    "description": "🍣 Цезарь — 10 шт\n🍣 Темпура — 10 шт\n\n🍟 Фри\n\n🍗 Крылышки — 14 шт\n\n🎁 В подарок: 🍕 Пицца Четыре сезона",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Pinto.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 20 шт суши + 🍟 фри + 🍗 крылышки + 🎁 пицца 4 сезона",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Темпура — 10 шт\n\n🍟 Фри\n\n🍗 Крылышки — 14 шт\n\n🎁 В подарок: 🍕 Пицца Четыре сезона",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-035",
    "categorySlug": "sets",
    "name": "Студент",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь маки — 10 шт\n\n🍗 Нагетсы — 8 шт\n\n🍟 Фри — 1 шт\n\n🧀 Сырные палочки — 6 шт\n\n🍕 Маргарита — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Student.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 20 шт суши + 🍗 нагетсы + 🍟 фри + 🧀 сырные палочки + 🍕 маргарита",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь маки — 10 шт\n\n🍗 Нагетсы — 8 шт\n\n🍟 Фри — 1 шт\n\n🧀 Сырные палочки — 6 шт\n\n🍕 Маргарита — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-036",
    "categorySlug": "sets",
    "name": "Запеченный",
    "description": "🍣 Цезарь запечённый — 20 шт\n\n🍗 Крылышки — 7 шт\n\n🍕 4 сезона — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Zapechenni.jpg",
    "sellingPrice": 6490,
    "costPrice": 4410,
    "setBuilderPrice": 6490,
    "weight": "🍣 20 шт суши + 🍗 крылышки + 🍕 4 сезона",
    "ingredients": "🍣 Цезарь запечённый — 20 шт\n\n🍗 Крылышки — 7 шт\n\n🍕 4 сезона — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-037",
    "categorySlug": "sets",
    "name": "Томи",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь маки — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍗 Нагетсы — 8 шт\n\n🍟 Фри — 1 шт\n\n🧀 Сырные палочки — 6 шт\n\n🍕 4 Сезона — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Tomi.jpg",
    "sellingPrice": 8490,
    "costPrice": 5770,
    "setBuilderPrice": 8490,
    "weight": "🍣 20 шт суши + 🍗 нагетсы + 🍟 фри + 🧀 палочки + 🍕 маргарита",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь маки — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍗 Нагетсы — 8 шт\n\n🍟 Фри — 1 шт\n\n🧀 Сырные палочки — 6 шт\n\n🍕 4 Сезона — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-038",
    "categorySlug": "sets",
    "name": "Коста",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍕 4 сезона — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Kosta.jpg",
    "sellingPrice": 7490,
    "costPrice": 5090,
    "setBuilderPrice": 7490,
    "weight": "🍣 30 шт суши + 🍗 крылышки + 🍕 4 сезона",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍕 4 сезона — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-039",
    "categorySlug": "sets",
    "name": "Оригами",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Бонито — 10 шт\n🍣 Ролл сердечка — 10 шт\n🍣 Инь Янъ — 20 шт\n\n🍕 Пеперони — 1 шт\n\n🍗 Нагетсы — 6 шт\n\n🍟 Фри — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Origami.jpg",
    "sellingPrice": 12500,
    "costPrice": 8500,
    "setBuilderPrice": 12500,
    "weight": "🍣 90 шт суши + 🍗 нагетсы + 🍟 фри + 🍕 пеперони",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Бонито — 10 шт\n🍣 Ролл сердечка — 10 шт\n🍣 Инь Янъ — 20 шт\n\n🍕 Пеперони — 1 шт\n\n🍗 Нагетсы — 6 шт\n\n🍟 Фри — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-040",
    "categorySlug": "sets",
    "name": "Медия",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь с курицей — 20 шт\n🍣 Америкас лососьем — 10 шт\n🍣 Овощ. ролл — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍕 Пицца куриная — 1 шт\n\n🥤 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Meida.jpg",
    "sellingPrice": 9490,
    "costPrice": 6450,
    "setBuilderPrice": 9490,
    "weight": "🍣 50 шт суши + 🍗 крылышки + 🍕 куриная + 🥤 кола",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь с курицей — 20 шт\n🍣 Америкас лососьем — 10 шт\n🍣 Овощ. ролл — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍕 Пицца куриная — 1 шт\n\n🥤 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-041",
    "categorySlug": "sets",
    "name": "Манго",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Блэк Джек — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🥤 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Mango.jpg",
    "sellingPrice": 7990,
    "costPrice": 5430,
    "setBuilderPrice": 7990,
    "weight": "🍣 40 шт суши + 🍕 пеперони + 🥤 кола",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Блэк Джек — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🥤 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-042",
    "categorySlug": "sets",
    "name": "Бейкер",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Америка — 20 шт\n🍣 Цезарь — 20 шт\n\n🍕 Пеперони — 2 шт\n\n🍗 Крылышки — 7 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Beiker.jpg",
    "sellingPrice": 11990,
    "costPrice": 8150,
    "setBuilderPrice": 11990,
    "weight": "🍣 60 шт суши + 🍕 2 пиццы + 🍗 крылышки",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Америка — 20 шт\n🍣 Цезарь — 20 шт\n\n🍕 Пеперони — 2 шт\n\n🍗 Крылышки — 7 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-043",
    "categorySlug": "sets",
    "name": "Панда",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Калифорния запечённый — 10 шт\n🍣 Темпура — 10 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Panda.jpg",
    "sellingPrice": 7990,
    "costPrice": 5430,
    "setBuilderPrice": 7990,
    "weight": "🍣 40 шт суши + 🍕 пеперони",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Калифорния запечённый — 10 шт\n🍣 Темпура — 10 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-044",
    "categorySlug": "sets",
    "name": "Пусан",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n\n🟡 Шарики — 1 шт\n\n🍕 Пеперони — 2 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Pusan.jpg",
    "sellingPrice": 8990,
    "costPrice": 6110,
    "setBuilderPrice": 8990,
    "weight": "🍣 40 шт суши + 🟡 шарики + 🍕 2 пиццы",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n\n🟡 Шарики — 1 шт\n\n🍕 Пеперони — 2 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-045",
    "categorySlug": "sets",
    "name": "Рио",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка темпура — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n\n🍣 Америка - 10 шт \n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Rio.jpg",
    "sellingPrice": 7990,
    "costPrice": 5430,
    "setBuilderPrice": 7990,
    "weight": "🍣 50 шт суши + 🍕 пеперони",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка темпура — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n\n🍣 Америка - 10 шт \n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-046",
    "categorySlug": "sets",
    "name": "Лайнер",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Филадельфия маки — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь темп — 20 шт\n🍣 Бонито с краб — 10 шт\n🍣 ПАК ролл — 10 шт\n🍣 Зверь ролл — 10 шт\n🍣 Калифорния с тобик — 10 шт\n🍣 Америка маки — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 1 шт\n\n🍗 Крылышки — 30 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Lainer.jpg",
    "sellingPrice": 19990,
    "costPrice": 13590,
    "setBuilderPrice": 19990,
    "weight": "🍣 100 шт суши + 🍕 3 пиццы + 🍗 крылышки",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Филадельфия маки — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь темп — 20 шт\n🍣 Бонито с краб — 10 шт\n🍣 ПАК ролл — 10 шт\n🍣 Зверь ролл — 10 шт\n🍣 Калифорния с тобик — 10 шт\n🍣 Америка маки — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 1 шт\n\n🍗 Крылышки — 30 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-047",
    "categorySlug": "sets",
    "name": "Актив",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка темп — 10 шт\n🍣 Томато — 10 шт\n🍣 Цезарь запеч — 10 шт\n🍣 Криспи Цезарь — 10 шт\n🍣 Инь Янь — 10 шт\n\n🍕 Маргарита — 1 шт\n\n🍗 Нагетсы — 6 шт\n🍟 Фри — 1 шт\n\n🥤 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Aktiv.jpg",
    "sellingPrice": 9990,
    "costPrice": 6790,
    "setBuilderPrice": 9990,
    "weight": "🍣 60 шт суши + 🍕 пицца + 🍗 нагетсы + 🍟 фри + 🥤 кола",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка темп — 10 шт\n🍣 Томато — 10 шт\n🍣 Цезарь запеч — 10 шт\n🍣 Криспи Цезарь — 10 шт\n🍣 Инь Янь — 10 шт\n\n🍕 Маргарита — 1 шт\n\n🍗 Нагетсы — 6 шт\n🍟 Фри — 1 шт\n\n🥤 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-048",
    "categorySlug": "sets",
    "name": "Император",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Америка — 10 шт\n🍣 Ролл Блинчик — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍘 Саше — 4 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Imperator.jpg",
    "sellingPrice": 10490,
    "costPrice": 7130,
    "setBuilderPrice": 10490,
    "weight": "🍣 50 шт суши + 🍗 крылышки + 🍘 саше + 🍕 4 сезона + 🍟 фри",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Америка — 10 шт\n🍣 Ролл Блинчик — 10 шт\n\n🍗 Крылышки — 7 шт\n\n🍘 Саше — 4 шт\n\n🍕 4 сезона — 1 шт\n\n🍟 Фри — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-049",
    "categorySlug": "sets",
    "name": "Че там",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка темпура — 10 шт\n🍣 Цезарь темп — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n🍣 Бонито — 10 шт\n\n🍕 Маргарита — 1 шт\n🍟 Фри — 1 шт\n🥤 Кола — 1 л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-CheTam.jpg",
    "sellingPrice": 9490,
    "costPrice": 6450,
    "setBuilderPrice": 9490,
    "weight": "🍣 60 шт суши + 🍕 маргарита + 🍟 фри + 🥤 кола",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка темпура — 10 шт\n🍣 Цезарь темп — 10 шт\n🍣 Цезарь запечённый — 10 шт\n🍣 Капа маки — 10 шт\n🍣 Бонито — 10 шт\n\n🍕 Маргарита — 1 шт\n🍟 Фри — 1 шт\n🥤 Кола — 1 л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-050",
    "categorySlug": "sets",
    "name": "Вавилон",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Филадельфия маки — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь темп — 20 шт\n🍣 Бонито краб — 10 шт\n🍣 ПАК ролл — 10 шт\n🍣 Зверь ролл — 10 шт\n🍣 Калифорния с тобико — 10 шт\n🍣 Америка маки — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Vavilon.jpg",
    "sellingPrice": 16490,
    "costPrice": 11210,
    "setBuilderPrice": 16490,
    "weight": "🍣 100 шт суши + 🍕 3 пицца",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Филадельфия маки — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь темп — 20 шт\n🍣 Бонито краб — 10 шт\n🍣 ПАК ролл — 10 шт\n🍣 Зверь ролл — 10 шт\n🍣 Калифорния с тобико — 10 шт\n🍣 Америка маки — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-051",
    "categorySlug": "sets",
    "name": "Великолепный",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Инь Янь — 10 шт\n🍣 Темпура — 30 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍣 Цезарь — 20 шт\n🍕 Пеперони — 1 шт\n🍕 Маргарита — 1 шт\n🍕 4 сезона — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Velikolepni.jpg",
    "sellingPrice": 15990,
    "costPrice": 10870,
    "setBuilderPrice": 15990,
    "weight": "🍣 100 шт суши + 🍕 3 пицца",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Инь Янь — 10 шт\n🍣 Темпура — 30 шт\n🍣 Цезарь запечённый — 10 шт\n\n🍣 Цезарь — 20 шт\n🍕 Пеперони — 1 шт\n🍕 Маргарита — 1 шт\n🍕 4 сезона — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-052",
    "categorySlug": "sets",
    "name": "Космос",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Калифорния с тобико — 10 шт\n🍣 Инь Янь — 10 шт\n🍣 Цезарь темп — 30 шт\n🍣 Америка — 30 шт\n\n🍕 4 сезона — 1 шт\n🍕 Маргарита — 1 шт\n🍕 Пеперони — 2 шт\n🍕 Грибная — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Kosmos.jpg",
    "sellingPrice": 18990,
    "costPrice": 12910,
    "setBuilderPrice": 18990,
    "weight": "🍣 100 шт суши + 🍕 5 Пицца",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Калифорния с тобико — 10 шт\n🍣 Инь Янь — 10 шт\n🍣 Цезарь темп — 30 шт\n🍣 Америка — 30 шт\n\n🍕 4 сезона — 1 шт\n🍕 Маргарита — 1 шт\n🍕 Пеперони — 2 шт\n🍕 Грибная — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-053",
    "categorySlug": "sets",
    "name": "Экономный",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Темпура — 10 шт\n🍣 Капа маки — 10 шт\n🍣 Сяке маки — 10 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Economni.jpg",
    "sellingPrice": 8990,
    "costPrice": 6110,
    "setBuilderPrice": 8990,
    "weight": "🍣 60 шт суши + 🍕 пеперони",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Темпура — 10 шт\n🍣 Капа маки — 10 шт\n🍣 Сяке маки — 10 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-054",
    "categorySlug": "sets",
    "name": "Шарага",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Каппа маки — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🥤 Кола — 1л",
    "imageUrl": null,
    "sellingPrice": 7000,
    "costPrice": 4760,
    "setBuilderPrice": 7000,
    "weight": "🍣 50 шт суши + 🍕 пицца + 🥤 кола",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Каппа маки — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🥤 Кола — 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-055",
    "categorySlug": "sets",
    "name": "Тик ток",
    "description": "🍣 Филадельфия — 40 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 30 шт\n🍣 ПАК ролл — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Блинчик — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 4 Сезона — 2 шт\n\n🍗 Нагетсы — 6 шт\n🍟 Фри — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-TikTok.jpg",
    "sellingPrice": 23490,
    "costPrice": 15970,
    "setBuilderPrice": 23490,
    "weight": "🍣 120 шт суши + 🍕 4 пицца + 🍗 нагетсы + 🍟 фри",
    "ingredients": "🍣 Филадельфия — 40 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 30 шт\n🍣 ПАК ролл — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Блинчик — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 4 Сезона — 2 шт\n\n🍗 Нагетсы — 6 шт\n🍟 Фри — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-056",
    "categorySlug": "sets",
    "name": "Саламалейкум",
    "description": "🍣 Цезарь — 20 шт\n🍣 Филадельфия — 20 шт\n🍣 Америка — 20 шт\n🍣 Овощной — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Цезарь запеченный — 20 шт\n\n🍔 Бургер — 4шт\n\n🍗 крылышки — 16 шт\n\n🍕 Пеперони — 3 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Salamalekum.jpg",
    "sellingPrice": 22500,
    "costPrice": 15300,
    "setBuilderPrice": 22500,
    "weight": "🍣 100 шт суши + 🍔 4 бургер + 🍗 крылышки + 🍕 3 пицца",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Филадельфия — 20 шт\n🍣 Америка — 20 шт\n🍣 Овощной — 10 шт\n🍣 Калифорния — 10 шт\n🍣 Цезарь запеченный — 20 шт\n\n🍔 Бургер — 4шт\n\n🍗 крылышки — 16 шт\n\n🍕 Пеперони — 3 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-057",
    "categorySlug": "sets",
    "name": "Санта-Круз",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 20 шт\n🍣 Цезарь — 10 шт\n\n🍕 Маргарита — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-SantaKruz.jpg",
    "sellingPrice": 7500,
    "costPrice": 5100,
    "setBuilderPrice": 7500,
    "weight": "🍣 40 шт суши + 🍕 пицца",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 20 шт\n🍣 Цезарь — 10 шт\n\n🍕 Маргарита — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-058",
    "categorySlug": "sets",
    "name": "Сараагаш",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Томато — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Инь-Янь — 10 шт\n\n🍕 Маргарита — 1 шт\n\n🍗 Нагетсы — 6 шт\n🍟 Фри 1\n\n🥤 Кола 1л",
    "imageUrl": null,
    "sellingPrice": 7300,
    "costPrice": 4960,
    "setBuilderPrice": 7300,
    "weight": "🍣 60 шт суши + 🍕 пицца + 🍗 нагетсы + 🍟 фри + 🥤 кола",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Томато — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Инь-Янь — 10 шт\n\n🍕 Маргарита — 1 шт\n\n🍗 Нагетсы — 6 шт\n🍟 Фри 1\n\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-059",
    "categorySlug": "sets",
    "name": "Сарыагаш",
    "description": "🍣 Цезарь — 30 шт\n🍣 Америка — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Капа-маки — 10 шт\n\n🍕 Пеперони — 2 шт\n\n🌭 Корндог — 5 шт\n🍟 1 — Фри\n🟡 1 — Шарики\n\n🥤 Кола 1л",
    "imageUrl": null,
    "sellingPrice": 11000,
    "costPrice": 7480,
    "setBuilderPrice": 11000,
    "weight": "🍣 70 шт суши + 🌭 корн-дог + 🍟 фри + 🍕 2 пиццы + 🟡 шарики + 🥤 кола",
    "ingredients": "🍣 Цезарь — 30 шт\n🍣 Америка — 20 шт\n🍣 Калифорния — 10 шт\n🍣 Капа-маки — 10 шт\n\n🍕 Пеперони — 2 шт\n\n🌭 Корндог — 5 шт\n🍟 1 — Фри\n🟡 1 — Шарики\n\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-060",
    "categorySlug": "sets",
    "name": "Пират",
    "description": "🍣 Филадельфия — 40 шт\n🍣 Америка — 60 шт\n🍣 Цезарь — 60 шт\n🍣 Калифорния — 20 шт\n🍣 Гейша — 20 шт\n\n🍕 4 Сезона — 1 шт\n🍕 Маргарита — 1 шт\n🍕 Пеперони — 2 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Pirat.jpg",
    "sellingPrice": 28000,
    "costPrice": 19040,
    "setBuilderPrice": 28000,
    "weight": "🍣 200 шт суши + 🍕 4 пиццы",
    "ingredients": "🍣 Филадельфия — 40 шт\n🍣 Америка — 60 шт\n🍣 Цезарь — 60 шт\n🍣 Калифорния — 20 шт\n🍣 Гейша — 20 шт\n\n🍕 4 Сезона — 1 шт\n🍕 Маргарита — 1 шт\n🍕 Пеперони — 2 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-061",
    "categorySlug": "sets",
    "name": "Муфаса",
    "description": "🍣 Гейша — 10 шт\n🍣 Филадельфия — 10 шт\n🍣 Америка — 20 шт\n🍣 Цезарь — 20 шт\n\n🍕 Пеперони — 2 шт\n🍕 4 Сезона — 1 шт\n\n🍔 Бургер — 4 шт\n🍗 Крылышки — 8 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Mufasa.jpg",
    "sellingPrice": 16000,
    "costPrice": 10880,
    "setBuilderPrice": 16000,
    "weight": "🍣 60 шт суши + 🍕 3 пиццы + 🍔 3 бургер + 🍗 крылышки",
    "ingredients": "🍣 Гейша — 10 шт\n🍣 Филадельфия — 10 шт\n🍣 Америка — 20 шт\n🍣 Цезарь — 20 шт\n\n🍕 Пеперони — 2 шт\n🍕 4 Сезона — 1 шт\n\n🍔 Бургер — 4 шт\n🍗 Крылышки — 8 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-062",
    "categorySlug": "sets",
    "name": "Народный",
    "description": "🍣 Цезарь запеченный — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🍟 Фри — 2 шт\n🌯 Лаваш — 1 шт\n🍔 Бургер — 2 шт\n\n🥤 Кола 1л",
    "imageUrl": null,
    "sellingPrice": 8500,
    "costPrice": 5780,
    "setBuilderPrice": 8500,
    "weight": "🍣 10 шт суши + 🌯 лаваш + 🍕 пицца + 🍟 фри + 🍔 2 бургер + 🥤 кола",
    "ingredients": "🍣 Цезарь запеченный — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🍟 Фри — 2 шт\n🌯 Лаваш — 1 шт\n🍔 Бургер — 2 шт\n\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-063",
    "categorySlug": "sets",
    "name": "Нью-Йорк",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n\n🍕 Маргарита — 1 шт",
    "imageUrl": null,
    "sellingPrice": 5500,
    "costPrice": 3740,
    "setBuilderPrice": 5500,
    "weight": "🍣 40 шт суши + 🍕 пицца",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n\n🍕 Маргарита — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-064",
    "categorySlug": "sets",
    "name": "Особое",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🌯 Лаваш — 1 шт\n🍔 Бургер — 1 шт\n🍟 Фри — 1 шт\n\n🥤 Кола 1д",
    "imageUrl": null,
    "sellingPrice": 7000,
    "costPrice": 4760,
    "setBuilderPrice": 7000,
    "weight": "🍣 20 шт суши + 🌯 лаваш + 🍟 фри + 🍔 бургер + 🥤 кола",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🌯 Лаваш — 1 шт\n🍔 Бургер — 1 шт\n🍟 Фри — 1 шт\n\n🥤 Кола 1д",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-065",
    "categorySlug": "sets",
    "name": "Пак",
    "description": "🍣 Калифорния — 10 шт\n🍣 Капа-маки — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🥤 Кола 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Pak.jpeg",
    "sellingPrice": 7000,
    "costPrice": 4760,
    "setBuilderPrice": 7000,
    "weight": "🍣 50 шт суши + 🍕 пицца + 🥤 кола",
    "ingredients": "🍣 Калифорния — 10 шт\n🍣 Капа-маки — 10 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-066",
    "categorySlug": "sets",
    "name": "Любимый",
    "description": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 1 шт\n\n🍟 Фри — 1 шт \n\n🥤 Кола 1л",
    "imageUrl": null,
    "sellingPrice": 9500,
    "costPrice": 6460,
    "setBuilderPrice": 9500,
    "weight": "🍣 20 шт суши + 🍕 3 пиццы + 🍟 фри + 🥤 кола",
    "ingredients": "🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 1 шт\n\n🍟 Фри — 1 шт \n\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-067",
    "categorySlug": "sets",
    "name": "Мега",
    "description": "🍕 Пеперони — 3 шт\n🍕 4 Сезона — 1 шт\n🍕 Сырный — 1 шт\n\n🍣 Цезарь запеченный — 10 шт\n\n🍗 Крылышки — 8 шт\n🍟 Фри — 2 шт\n\n🎁🎁🎁\n🥤 Кола 2л",
    "imageUrl": null,
    "sellingPrice": 14500,
    "costPrice": 9860,
    "setBuilderPrice": 14500,
    "weight": "🍕 5 пиццы + 🍣 10 шт суши + 🍗 крылышки + 🍟 2 фри + 🎁 2л кола",
    "ingredients": "🍕 Пеперони — 3 шт\n🍕 4 Сезона — 1 шт\n🍕 Сырный — 1 шт\n\n🍣 Цезарь запеченный — 10 шт\n\n🍗 Крылышки — 8 шт\n🍟 Фри — 2 шт\n\n🎁🎁🎁\n🥤 Кола 2л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-068",
    "categorySlug": "sets",
    "name": "Корпаратив",
    "description": "🍕 Пеперони — 2 шт\n🍕 Сырный — 1 шт\n\n🌯 Лаваш — 2 шт\n🍔 Бургер — 1 шт\n🍟 Фри — 1 шт\n\n🎁🎁🎁\n🥤 Кола 2л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Korporativ.jpg",
    "sellingPrice": 24990,
    "costPrice": 16990,
    "setBuilderPrice": 24990,
    "weight": "🍕 3 пиццы + 🌯 2 лаваш + 🍔 бургер + 🍟 фри + 🎁 2л кола",
    "ingredients": "🍕 Пеперони — 2 шт\n🍕 Сырный — 1 шт\n\n🌯 Лаваш — 2 шт\n🍔 Бургер — 1 шт\n🍟 Фри — 1 шт\n\n🎁🎁🎁\n🥤 Кола 2л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-069",
    "categorySlug": "sets",
    "name": "Катя",
    "description": "🍣 Цезарь — 20 шт\n🍣 Капа-маки — 20 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт",
    "imageUrl": null,
    "sellingPrice": 7000,
    "costPrice": 4760,
    "setBuilderPrice": 7000,
    "weight": "🍣 50 шт суши + 🍕 пицца",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Капа-маки — 20 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-070",
    "categorySlug": "sets",
    "name": "Зал",
    "description": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🎁🎁🎁\n🥤 Кола 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Zal.jpg",
    "sellingPrice": 7000,
    "costPrice": 4760,
    "setBuilderPrice": 7000,
    "weight": "🍣 40 шт суши + 🍕 пицца + 🎁 кола",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Америка — 10 шт\n🍣 Калифорния — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🎁🎁🎁\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-071",
    "categorySlug": "sets",
    "name": "Комбо 1",
    "description": "🍔 Бургер — 2 шт\n\n🍣 Цезарь — 10 шт\n\n🍟 Фри — 1 шт\n\n🎁🎁🎁\n🥤 Кола 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Kombo1.jpg",
    "sellingPrice": 4800,
    "costPrice": 3260,
    "setBuilderPrice": 4800,
    "weight": "🍔 2 бургер + 🍣 10 шт суши + 🍟 фри + 🎁 кола",
    "ingredients": "🍔 Бургер — 2 шт\n\n🍣 Цезарь — 10 шт\n\n🍟 Фри — 1 шт\n\n🎁🎁🎁\n🥤 Кола 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-072",
    "categorySlug": "sets",
    "name": "Комбо 2",
    "description": "🍔 Бургер — 2 шт\n🌯 Лаваш — 1 шт\n🍟 Фри — 1 шт\n\n🍣 Цезарь — 10 шт\n\n🎁🎁🎁\n🥤 Fuse-tea 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Kombo2.jpg",
    "sellingPrice": 6500,
    "costPrice": 4420,
    "setBuilderPrice": 6500,
    "weight": "🍔 2 бургер + 🌯 лаваш + 🍟 фри + 🍣 10 шт суши + 🎁 fuse-tea",
    "ingredients": "🍔 Бургер — 2 шт\n🌯 Лаваш — 1 шт\n🍟 Фри — 1 шт\n\n🍣 Цезарь — 10 шт\n\n🎁🎁🎁\n🥤 Fuse-tea 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-073",
    "categorySlug": "sets",
    "name": "Комбо 3",
    "description": "🍔 Бургер — 3 шт\n🌯 Лаваш — 2 шт\n🍟 Фри — 1 шт\n\n🍣 Цезарь — 10 шт\n\n🎁🎁🎁\n🥤 Coca-cola 1л",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Kombo3.jpg",
    "sellingPrice": 8000,
    "costPrice": 5440,
    "setBuilderPrice": 8000,
    "weight": "🍔 3 бургер + 🌯 2 лаваш + 🍟 фри + 🍣 10 шт суши + 🎁 coca-cola",
    "ingredients": "🍔 Бургер — 3 шт\n🌯 Лаваш — 2 шт\n🍟 Фри — 1 шт\n\n🍣 Цезарь — 10 шт\n\n🎁🎁🎁\n🥤 Coca-cola 1л",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-074",
    "categorySlug": "sets",
    "name": "Комбо 5",
    "description": "🍔 Бургер — 5 шт\n\n🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🍟 Фри — 2 шт\n\n🎁🎁🎁\n🥤 Кола 2л  ",
    "imageUrl": null,
    "sellingPrice": 10000,
    "costPrice": 6800,
    "setBuilderPrice": 10000,
    "weight": "🍔 5 бургер + 🍣 20 шт суши + 🍟 2 фри + 🎁 2л coca-cola",
    "ingredients": "🍔 Бургер — 5 шт\n\n🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🍟 Фри — 2 шт\n\n🎁🎁🎁\n🥤 Кола 2л  ",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-075",
    "categorySlug": "sets",
    "name": "Аригато",
    "description": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🍟 Фри — 1 шт\n🍔 Бургер(куриный) — 2 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Arigato.jpg",
    "sellingPrice": 9500,
    "costPrice": 6460,
    "setBuilderPrice": 9500,
    "weight": "🍣 40 шт суши + 🍕 пицца + 🍟 фри + 🍔 2 бургер",
    "ingredients": "🍣 Филадельфия — 10 шт\n🍣 Америка — 10 шт\n🍣 Цезарь — 10 шт\n🍣 Цезарь запеченный — 10 шт\n\n🍕 Пеперони — 1 шт\n\n🍟 Фри — 1 шт\n🍔 Бургер(куриный) — 2 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-076",
    "categorySlug": "sets",
    "name": "Атом",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 30 шт\n🍣 Аляска — 20 шт\n🍣 Калифорния запеченный — 10 шт\n🍣 Зеленый зверь — 20 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 2 шт\n🍕 4 Сезона — 2 шт\n\n🟡 Шарики\n🍗 Крылышки — 8 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Atom.jpg",
    "sellingPrice": 22290,
    "costPrice": 15160,
    "setBuilderPrice": 22290,
    "weight": "🍣 120 шт суши + 🍕 6 пиццы + 🟡 шарики + 🍗 крылышки",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 30 шт\n🍣 Аляска — 20 шт\n🍣 Калифорния запеченный — 10 шт\n🍣 Зеленый зверь — 20 шт\n\n🍕 Пеперони — 2 шт\n🍕 Маргарита — 2 шт\n🍕 4 Сезона — 2 шт\n\n🟡 Шарики\n🍗 Крылышки — 8 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-077",
    "categorySlug": "sets",
    "name": "Алматы",
    "description": "🍣 Цезарь — 20 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт\n🍕 4 Сезона — 1 шт\n\n🍘 Саше — 4 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Almaty.jpg",
    "sellingPrice": 9000,
    "costPrice": 6120,
    "setBuilderPrice": 9000,
    "weight": "🍣 40 шт суши + 🍕 2 пиццы + 🍘 саше",
    "ingredients": "🍣 Цезарь — 20 шт\n🍣 Цезарь запеченный — 10 шт\n🍣 Америка — 10 шт\n\n🍕 Пеперони — 1 шт\n🍕 4 Сезона — 1 шт\n\n🍘 Саше — 4 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sets-078",
    "categorySlug": "sets",
    "name": "Челлендж",
    "description": "🍣 Филадельфия — 20 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🍕 Пеперони — 1 шт\n🍕 4 Сезона — 1 шт",
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/sets/Set-Chellendge.jpg",
    "sellingPrice": 10500,
    "costPrice": 7140,
    "setBuilderPrice": 10500,
    "weight": "🍣 60 шт суши + 🍕 2 пиццы",
    "ingredients": "🍣 Филадельфия — 20 шт\n🍣 Цезарь — 20 шт\n🍣 Америка — 20 шт\n\n🍕 Пеперони — 1 шт\n🍕 4 Сезона — 1 шт",
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-sushi-001",
    "categorySlug": "sushi",
    "name": "Цезарь Classic",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Sezar-Cl.jpg",
    "sellingPrice": 1890,
    "costPrice": 1040,
    "setBuilderPrice": 1660,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-002",
    "categorySlug": "sushi",
    "name": "Цезарь с помидором",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Sezar-Pomidor.jpg",
    "sellingPrice": 1890,
    "costPrice": 1040,
    "setBuilderPrice": 1660,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-003",
    "categorySlug": "sushi",
    "name": "Цезарь запечённый",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Sezar-Zap.jpg",
    "sellingPrice": 1990,
    "costPrice": 1090,
    "setBuilderPrice": 1750,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-004",
    "categorySlug": "sushi",
    "name": "Сяке Темпура",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Sake-Tem.jpg",
    "sellingPrice": 2190,
    "costPrice": 1200,
    "setBuilderPrice": 1930,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-005",
    "categorySlug": "sushi",
    "name": "Филадельфия",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Filadelfia.jpg",
    "sellingPrice": 2190,
    "costPrice": 1200,
    "setBuilderPrice": 1930,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-006",
    "categorySlug": "sushi",
    "name": "Канада",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kanada.jpg",
    "sellingPrice": 2090,
    "costPrice": 1150,
    "setBuilderPrice": 1840,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-007",
    "categorySlug": "sushi",
    "name": "Унаги Темпура",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Unagi-Tem.jpg",
    "sellingPrice": 2190,
    "costPrice": 1200,
    "setBuilderPrice": 1930,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-008",
    "categorySlug": "sushi",
    "name": "Аляска",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Alyaska.jpg",
    "sellingPrice": 1890,
    "costPrice": 1040,
    "setBuilderPrice": 1660,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-009",
    "categorySlug": "sushi",
    "name": "Калифорния с крабом",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kalifornia.jpg",
    "sellingPrice": 1890,
    "costPrice": 1040,
    "setBuilderPrice": 1660,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-010",
    "categorySlug": "sushi",
    "name": "Калифорния с ласосьем",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kalifornia.jpg",
    "sellingPrice": 2090,
    "costPrice": 1150,
    "setBuilderPrice": 1840,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-011",
    "categorySlug": "sushi",
    "name": "Калифорния запечённый",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kalifornia-zap.jpg",
    "sellingPrice": 1990,
    "costPrice": 1090,
    "setBuilderPrice": 1750,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-012",
    "categorySlug": "sushi",
    "name": "Бонита",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Bonita.jpg",
    "sellingPrice": 1790,
    "costPrice": 980,
    "setBuilderPrice": 1580,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-013",
    "categorySlug": "sushi",
    "name": "Сингапур",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Singapure.jpg",
    "sellingPrice": 2090,
    "costPrice": 1150,
    "setBuilderPrice": 1840,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-014",
    "categorySlug": "sushi",
    "name": "Капа Маки",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kapa-Maki.jpg",
    "sellingPrice": 890,
    "costPrice": 490,
    "setBuilderPrice": 780,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-015",
    "categorySlug": "sushi",
    "name": "Капа-маки с ласосьем запечённый",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Zap-SUgr.jpg",
    "sellingPrice": 2190,
    "costPrice": 1200,
    "setBuilderPrice": 1930,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-016",
    "categorySlug": "sushi",
    "name": "Дракон (с помидором)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Drakon-Lasos.jpg",
    "sellingPrice": 1890,
    "costPrice": 1040,
    "setBuilderPrice": 1660,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-017",
    "categorySlug": "sushi",
    "name": "Сяке Запечённый",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Sake-Zap.jpg",
    "sellingPrice": 2390,
    "costPrice": 1310,
    "setBuilderPrice": 2100,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-018",
    "categorySlug": "sushi",
    "name": "Сяше пончик ласось",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Cyashe lasos.jpg",
    "sellingPrice": 2190,
    "costPrice": 1200,
    "setBuilderPrice": 1930,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-019",
    "categorySlug": "sushi",
    "name": "Сяше пончик куриный",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Cyashe lasos.jpg",
    "sellingPrice": 1990,
    "costPrice": 1090,
    "setBuilderPrice": 1750,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-sushi-020",
    "categorySlug": "sushi",
    "name": "Гункан",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Gunkan.jpg",
    "sellingPrice": 1290,
    "costPrice": 710,
    "setBuilderPrice": 1140,
    "weight": "10 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-pizza-001",
    "categorySlug": "pizza",
    "name": "Маргарита",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Pizza-Margarita.jpg",
    "sellingPrice": 2090,
    "costPrice": 1090,
    "setBuilderPrice": 1840,
    "weight": "30 см",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-pizza-002",
    "categorySlug": "pizza",
    "name": "4 Сезона",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Pizza-4Sezon.jpg",
    "sellingPrice": 2390,
    "costPrice": 1240,
    "setBuilderPrice": 2100,
    "weight": "30 см",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-pizza-003",
    "categorySlug": "pizza",
    "name": "Пепперони",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Pizza-Peperoni.jpg",
    "sellingPrice": 2090,
    "costPrice": 1090,
    "setBuilderPrice": 1840,
    "weight": "30 см",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-pizza-004",
    "categorySlug": "pizza",
    "name": "Сырный",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Pizza-Boloneze.jpg",
    "sellingPrice": 1890,
    "costPrice": 980,
    "setBuilderPrice": 1660,
    "weight": "30 см",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-pizza-005",
    "categorySlug": "pizza",
    "name": "Куриная",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Pizza-Chiken.jpg",
    "sellingPrice": 2090,
    "costPrice": 1090,
    "setBuilderPrice": 1840,
    "weight": "30 см",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-001",
    "categorySlug": "snacks",
    "name": "Лаваш (Куриный)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Lavash.jpg",
    "sellingPrice": 1290,
    "costPrice": 650,
    "setBuilderPrice": 1140,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-002",
    "categorySlug": "snacks",
    "name": "Лаваш (Куриный Сыр)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Lavash-Kurini.jpg",
    "sellingPrice": 1390,
    "costPrice": 700,
    "setBuilderPrice": 1220,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-003",
    "categorySlug": "snacks",
    "name": "Лаваш (Говяжий)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Lavash.jpg",
    "sellingPrice": 1290,
    "costPrice": 650,
    "setBuilderPrice": 1140,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-004",
    "categorySlug": "snacks",
    "name": "Лаваш (Говяжий Сыр)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Lavash-Goviazhi.jpg",
    "sellingPrice": 1390,
    "costPrice": 700,
    "setBuilderPrice": 1220,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-005",
    "categorySlug": "snacks",
    "name": "Бургер (Куриный)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Burger-K.jpg",
    "sellingPrice": 1190,
    "costPrice": 600,
    "setBuilderPrice": 1050,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-006",
    "categorySlug": "snacks",
    "name": "ЧизБургер (Куриный)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Burger-K.jpg",
    "sellingPrice": 1290,
    "costPrice": 650,
    "setBuilderPrice": 1140,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-007",
    "categorySlug": "snacks",
    "name": "Биг ЧизБургер (Куриный)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Burger-K2x.jpg",
    "sellingPrice": 1690,
    "costPrice": 850,
    "setBuilderPrice": 1490,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-008",
    "categorySlug": "snacks",
    "name": "Бургер (Говяжий)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Burger-G.jpg",
    "sellingPrice": 1390,
    "costPrice": 700,
    "setBuilderPrice": 1220,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-009",
    "categorySlug": "snacks",
    "name": "ЧизБургер (Говяжий)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Burger-G.jpg",
    "sellingPrice": 1490,
    "costPrice": 750,
    "setBuilderPrice": 1310,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-010",
    "categorySlug": "snacks",
    "name": "Биг ЧизБургер (Говяжий)",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Burger-G2x.jpg",
    "sellingPrice": 1790,
    "costPrice": 900,
    "setBuilderPrice": 1580,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-011",
    "categorySlug": "snacks",
    "name": "Нагетсы 8шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Nagetsi.jpg",
    "sellingPrice": 1490,
    "costPrice": 750,
    "setBuilderPrice": 1310,
    "weight": "8 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-012",
    "categorySlug": "snacks",
    "name": "Кортофельные шарики 16шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/K-Shariki.jpg",
    "sellingPrice": 700,
    "costPrice": 350,
    "setBuilderPrice": 620,
    "weight": "16 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-013",
    "categorySlug": "snacks",
    "name": "Фри",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Free.jpg",
    "sellingPrice": 700,
    "costPrice": 350,
    "setBuilderPrice": 620,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-014",
    "categorySlug": "snacks",
    "name": "Куриные крылышки 8шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Krilishki.jpg",
    "sellingPrice": 1490,
    "costPrice": 750,
    "setBuilderPrice": 1310,
    "weight": "8 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-015",
    "categorySlug": "snacks",
    "name": "Куриные крылышки 16шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Krilishki.jpg",
    "sellingPrice": 2790,
    "costPrice": 1400,
    "setBuilderPrice": 2460,
    "weight": "16 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-016",
    "categorySlug": "snacks",
    "name": "Куриные крылышки 24шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Krilishki.jpg",
    "sellingPrice": 4280,
    "costPrice": 2140,
    "setBuilderPrice": 3770,
    "weight": "24 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-017",
    "categorySlug": "snacks",
    "name": "Куриные крылышки 32шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Krilishki.jpg",
    "sellingPrice": 5580,
    "costPrice": 2790,
    "setBuilderPrice": 4910,
    "weight": "32 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-018",
    "categorySlug": "snacks",
    "name": "Корн дог 5шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Korn-Dog.jpg",
    "sellingPrice": 1290,
    "costPrice": 650,
    "setBuilderPrice": 1140,
    "weight": "5 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-snacks-019",
    "categorySlug": "snacks",
    "name": "Сырные палочки 6шт",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/S-Palochki.jpg",
    "sellingPrice": 1290,
    "costPrice": 650,
    "setBuilderPrice": 1140,
    "weight": "6 шт",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": true
  },
  {
    "id": "seed-drinks-001",
    "categorySlug": "drinks",
    "name": "Фанта 1л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Fanta.png",
    "sellingPrice": 700,
    "costPrice": 430,
    "setBuilderPrice": 700,
    "weight": "1 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-002",
    "categorySlug": "drinks",
    "name": "Кола 1л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kola.jpg",
    "sellingPrice": 700,
    "costPrice": 430,
    "setBuilderPrice": 700,
    "weight": "1 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-003",
    "categorySlug": "drinks",
    "name": "Фьюс-ти 1л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Fuse.jpg",
    "sellingPrice": 700,
    "costPrice": 430,
    "setBuilderPrice": 700,
    "weight": "1 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-004",
    "categorySlug": "drinks",
    "name": "Макси чай 1л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Maxi.jpg",
    "sellingPrice": 700,
    "costPrice": 320,
    "setBuilderPrice": 700,
    "weight": "1 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-005",
    "categorySlug": "drinks",
    "name": "Пепси 1л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Pepsi.jpg",
    "sellingPrice": 700,
    "costPrice": 430,
    "setBuilderPrice": 700,
    "weight": "1 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-006",
    "categorySlug": "drinks",
    "name": "Пико сок 1л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Piko.png",
    "sellingPrice": 800,
    "costPrice": 500,
    "setBuilderPrice": 800,
    "weight": "1 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-007",
    "categorySlug": "drinks",
    "name": "Фанта 2л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Fanta-2l.jpg",
    "sellingPrice": 900,
    "costPrice": 560,
    "setBuilderPrice": 900,
    "weight": "2 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-008",
    "categorySlug": "drinks",
    "name": "Кола 2л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Kola-2l",
    "sellingPrice": 900,
    "costPrice": 560,
    "setBuilderPrice": 900,
    "weight": "2 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-009",
    "categorySlug": "drinks",
    "name": "Макси чай 2л",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Maxi-2l.jpg",
    "sellingPrice": 900,
    "costPrice": 410,
    "setBuilderPrice": 900,
    "weight": "2 л",
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-010",
    "categorySlug": "drinks",
    "name": "Горилла",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Gorilla.jpg",
    "sellingPrice": 600,
    "costPrice": 370,
    "setBuilderPrice": 600,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-011",
    "categorySlug": "drinks",
    "name": "Диззи",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Dizzy.png",
    "sellingPrice": 600,
    "costPrice": 370,
    "setBuilderPrice": 600,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-012",
    "categorySlug": "drinks",
    "name": "Чай бокал",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Tea-Cup.jpg",
    "sellingPrice": 150,
    "costPrice": 70,
    "setBuilderPrice": 150,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-013",
    "categorySlug": "drinks",
    "name": "Чай чайник",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Tea.jpg",
    "sellingPrice": 300,
    "costPrice": 140,
    "setBuilderPrice": 300,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-014",
    "categorySlug": "drinks",
    "name": "Кофе бокал",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Coffee-Cup.jpg",
    "sellingPrice": 200,
    "costPrice": 90,
    "setBuilderPrice": 200,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-015",
    "categorySlug": "drinks",
    "name": "Кофе 3в1",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Coffee-3v1.jpg",
    "sellingPrice": 300,
    "costPrice": 140,
    "setBuilderPrice": 300,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-016",
    "categorySlug": "drinks",
    "name": "Айран",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Ayran.jpg",
    "sellingPrice": 250,
    "costPrice": 110,
    "setBuilderPrice": 250,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-017",
    "categorySlug": "drinks",
    "name": "Нан",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Nan.jpg",
    "sellingPrice": 150,
    "costPrice": 70,
    "setBuilderPrice": 150,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-018",
    "categorySlug": "drinks",
    "name": "Чесночный соус",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Ch-Sous.jpg",
    "sellingPrice": 150,
    "costPrice": 50,
    "setBuilderPrice": 150,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-019",
    "categorySlug": "drinks",
    "name": "Сырный соус",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/S-Sous.jpg",
    "sellingPrice": 150,
    "costPrice": 50,
    "setBuilderPrice": 150,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-020",
    "categorySlug": "drinks",
    "name": "Томатный соус",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/T-Sous.jpg",
    "sellingPrice": 150,
    "costPrice": 50,
    "setBuilderPrice": 150,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  },
  {
    "id": "seed-drinks-021",
    "categorySlug": "drinks",
    "name": "Халапеньо",
    "description": null,
    "imageUrl": "https://raw.githubusercontent.com/Paksushi-Saryagash/paksushi-webapp/main/public/menu-assets/blyudo/Halapeno.png",
    "sellingPrice": 150,
    "costPrice": 50,
    "setBuilderPrice": 150,
    "weight": null,
    "ingredients": null,
    "isAvailable": true,
    "isActive": true,
    "isSetBuilderEnabled": false
  }
] as const;

const obsoleteSeedItemIds = [
  "seed-set-hit",
  "seed-set-family",
  "seed-set-baked",
  "seed-set-mini",
  "seed-sushi-philadelphia",
  "seed-sushi-california",
  "seed-sushi-canada",
  "seed-sushi-tempura",
  "seed-sushi-baked-salmon",
  "seed-sushi-baked-chicken",
  "seed-sushi-ebi",
  "seed-sushi-sake-maki",
  "seed-sushi-kappa-maki",
  "seed-pizza-pepperoni",
  "seed-pizza-margarita",
  "seed-pizza-chicken",
  "seed-pizza-4cheese",
  "seed-pizza-assorti",
  "seed-snack-fries",
  "seed-snack-nuggets",
  "seed-snack-cheese-sticks",
  "seed-snack-wings",
  "seed-drink-cola",
  "seed-drink-fanta",
  "seed-drink-sprite",
  "seed-drink-water"
] as const;

async function main() {
  const ownerPasswordHash = await bcrypt.hash("owner12345", 12);
  const operatorPasswordHash = await bcrypt.hash("operator12345", 12);

  await prisma.user.upsert({
    where: { login: "owner" },
    update: {},
    create: {
      name: "Владелец Pak Sushi",
      login: "owner",
      passwordHash: ownerPasswordHash,
      role: UserRole.OWNER
    }
  });

  await prisma.user.upsert({
    where: { login: "operator" },
    update: {},
    create: {
      name: "Оператор",
      login: "operator",
      passwordHash: operatorPasswordHash,
      role: UserRole.OPERATOR
    }
  });

  for (const category of categories) {
    await prisma.menuCategory.upsert({
      where: { slug: category.slug },
      update: category,
      create: category
    });
  }

  const categoryRows = await prisma.menuCategory.findMany({
    where: { slug: { in: categories.map((category) => category.slug) } },
    select: { id: true, slug: true }
  });
  const categoryBySlug = new Map(categoryRows.map((category) => [category.slug, category.id]));

  await prisma.menuItem.updateMany({
    where: { id: { in: [...obsoleteSeedItemIds] } },
    data: {
      isActive: false,
      isAvailable: false,
      isSetBuilderEnabled: false
    }
  });

  for (const item of menuItems) {
    const categoryId = categoryBySlug.get(item.categorySlug);
    if (!categoryId) continue;

    const data = {
      name: item.name,
      description: item.description,
      categoryId,
      imageUrl: item.imageUrl,
      sellingPrice: item.sellingPrice,
      costPrice: item.costPrice,
      setBuilderPrice: item.setBuilderPrice,
      weight: item.weight,
      ingredients: item.ingredients,
      isAvailable: item.isAvailable,
      isActive: item.isActive,
      isSetBuilderEnabled: item.isSetBuilderEnabled
    };

    await prisma.menuItem.upsert({
      where: { id: item.id },
      update: data,
      create: { id: item.id, ...data }
    });
  }

  await prisma.setBuilderRule.upsert({
    where: { id: "default-set-rule" },
    update: {
      name: "Основное правило конструктора",
      threshold: 5000,
      isActive: true,
      useSetPriceSum: true
    },
    create: {
      id: "default-set-rule",
      name: "Основное правило конструктора",
      threshold: 5000,
      isActive: true,
      useSetPriceSum: true
    }
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
